---
title: "Arrival Times Visualizations"
author: "Kate Houston"
format: 
  html:
    self-contained: True
editor: visual
---

## Arrival Times Visualizations

```{r}
library(tidyverse)
library(readr)
```

```{r data}
data <- read_csv("data/cleaned_full_class_data.csv", show_col_types = FALSE)
```

```{r priority arrival times}
data |> 
  ggplot(aes(
    x = as.factor(priority), 
    y = secs_disp_to_arrv/60
    )) + 
  geom_boxplot(outlier.shape = NA) + 
  coord_cartesian(ylim = c(0, 60)) +
  labs(
    title = "Arrival Time Distribution by Call Priority", 
    x = 'Call Priority', 
    y = 'Arrival Time (minutes)') +
  theme_minimal()
```

```{r density plot}
data |> 
  mutate(priority = factor(priority, 
                           levels = c("P", "1", "2", "3", "4", "5", "6", "7", "8", "9"))) |> 
  ggplot(
    aes(
      x = secs_disp_to_arrv/60,
      color = priority,
      fill = priority    # <--- ADD fill = priority
    )
  ) + 
  geom_density(alpha = 0.1) +    # alpha makes the lines slightly transparent if you want
  coord_cartesian(xlim = c(0, 60)) +
  scale_x_continuous(breaks = seq(0, 60, by = 5)) +
  labs(
    title = 'Dispatch-to-Arrival Times by Call Priority',
    subtitle = 'Arrival time calculated as time from unit dispatch to arrival.',
    x = 'Arrival Time (minutes)',
    y = 'Density',
    color = 'Call Priority',
    fill = 'Call Priority'
  ) +
  theme_minimal() +
  facet_wrap(~agency)
```

```{r}
data |> 
  mutate(priority = factor(priority, 
                           levels = c("P", "1", "2", "3", "4", "5", "6", "7", "8", "9"))) |> 
  ggplot(
    aes(
      x = secs_to_arrv/60,
      color = priority,
      fill = priority    # <--- ADD fill = priority
    )
  ) + 
  geom_density(alpha = 0.1) +    # alpha makes the lines slightly transparent if you want
  coord_cartesian(xlim = c(0, 60)) +
  scale_x_continuous(breaks = seq(0, 60, by = 5)) +
  labs(
    title = 'Call-to-Arrival Times by Call Priority',
    subtitle = 'Arrival time calculated as time from time of call to arrival.',
    x = 'Arrival Time (minutes)',
    y = 'Density',
    color = 'Call Priority',
    fill = 'Call Priority'
  ) +
  theme_minimal() +
  facet_wrap(~agency)
```

```{r hist}
data |> 
  mutate(priority = factor(priority, 
                           levels = c("P", "1", "2", "3", "4", "5", "6", "7", "8", "9"))) |> 
  ggplot(
    aes(
      x = secs_disp_to_arrv/60,
      color = priority,
      fill = priority    # <--- ADD fill = priority
    )
  ) + 
  geom_histogram(alpha = 0.1) +    # alpha makes the lines slightly transparent if you want
  coord_cartesian(xlim = c(0, 60)) +
  scale_x_continuous(breaks = seq(0, 60, by = 5)) +
  labs(
    title = 'Dispatch-to-Arrival Times by Call Priority',
    subtitle = 'Arrival time calculated as time from unit dispatch to arrival.',
    x = 'Arrival Time (minutes)',
    y = 'Density',
    color = 'Call Priority',
    fill = 'Call Priority'
  ) +
  theme_minimal() +
  facet_wrap(~agency)
```
